// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_pZdvwJ1NHZFFtyLRm8Rtar5a9rbtFw',
    appId: '1:504603180621:web:93e1aee6f3f1a741ebe604',
    messagingSenderId: '504603180621',
    projectId: 'task-management-9db24',
    authDomain: 'task-management-9db24.firebaseapp.com',
    storageBucket: 'task-management-9db24.appspot.com',
    measurementId: 'G-G7WSL8LCZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAA6aImuFJsVQubDF6WGBhQbzLQ7_SAs',
    appId: '1:504603180621:android:e0cbb829b07a2757ebe604',
    messagingSenderId: '504603180621',
    projectId: 'task-management-9db24',
    storageBucket: 'task-management-9db24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzGwcKPscnVgGbPP6-l0OptAwmbh1-Kwc',
    appId: '1:504603180621:ios:300ed89c4e97ea04ebe604',
    messagingSenderId: '504603180621',
    projectId: 'task-management-9db24',
    storageBucket: 'task-management-9db24.appspot.com',
    iosClientId:
        '504603180621-v6patag83kguh059a8ani2kmb7e5pv67.apps.googleusercontent.com',
    iosBundleId: 'dev.dennismichol.taskmanagement',
  );
}
