name: Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install JAVA SDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check Flutter SDK Version
        run: flutter --version
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format . --output=none --set-exit-if-changed
      - name: Analyze project source
        run: flutter analyze
      - name: Execute Tests
        run: flutter test